-- V2 — Seed popular games (DEV ONLY)

INSERT INTO games (name, genre, release_year, image_url, max_party_size) VALUES
                                                                             ('Valorant',                  'Shooter',       2020, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9i1s.webp', 5),
                                                                             ('Counter-Strike 2',          'Shooter',       2023, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6yr1.webp', 5),
                                                                             ('League of Legends',         'MOBA',          2009, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co49wj.webp', 5),
                                                                             ('Dota 2',                    'MOBA',          2013, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8wz4.webp', 5),
                                                                             ('Fortnite',                  'Battle Royale', 2017, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8wv5.webp', 4),
                                                                             ('Apex Legends',              'Battle Royale', 2019, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co200w.webp', 3),
                                                                             ('Overwatch 2',               'Shooter',       2022, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5tkd.webp', 5),
                                                                             ('Minecraft',                 'Sandbox',       2011, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co49x5.webp', 10),
                                                                             ('Rocket League',             'Sports',        2015, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5w0w.webp', 3),
                                                                             ('Rainbow Six Siege',         'Shooter',       2015, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8hkb.webp', 5),
                                                                             ('World of Warcraft',         'MMO',           2004, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9ial.webp', 5),
                                                                             ('Destiny 2',                 'Shooter',       2017, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6r0a.webp', 6),
                                                                             ('PUBG: Battlegrounds',       'Battle Royale', 2017, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7mcl.webp', 4),
                                                                             ('Genshin Impact',            'RPG',           2020, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co480q.webp', 4),
                                                                             ('Call of Duty: Warzone',     'Battle Royale', 2020, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8dq1.webp', 4),
                                                                             ('Diablo IV',                 'RPG',           2023, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5w0r.webp', 4),
                                                                             ('Path of Exile 2',           'RPG',           2024, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8ncm.webp', 6),
                                                                             ('Sea of Thieves',            'Adventure',     2018, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7g.webp', 4),
                                                                             ('Dead by Daylight',          'Horror',        2016, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8bop.webp', 5),
                                                                             ('Helldivers 2',              'Shooter',       2024, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co73bh.webp', 4),
                                                                             ('Monster Hunter Wilds',      'RPG',           2025, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7jab.webp', 4),
                                                                             ('The Finals',                'Shooter',       2023, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7d41.webp', 3),
                                                                             ('Lethal Company',            'Horror',        2023, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7bji.webp', 4),
                                                                             ('Phasmophobia',              'Horror',        2020, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2k3n.webp', 4);