export interface Country {
  code: string
  native: string
  en: string
}

export const ALL_COUNTRIES: Country[] = [
  { code: 'AF', native: 'افغانستان', en: 'Afghanistan' },
  { code: 'AL', native: 'Shqipëria', en: 'Albania' },
  { code: 'DZ', native: 'الجزائر', en: 'Algeria' },
  { code: 'AD', native: 'Andorra', en: 'Andorra' },
  { code: 'AO', native: 'Angola', en: 'Angola' },
  { code: 'AG', native: 'Antigua and Barbuda', en: 'Antigua and Barbuda' },
  { code: 'AR', native: 'Argentina', en: 'Argentina' },
  { code: 'AM', native: 'Հայաստան', en: 'Armenia' },
  { code: 'AU', native: 'Australia', en: 'Australia' },
  { code: 'AT', native: 'Österreich', en: 'Austria' },
  { code: 'AZ', native: 'Azərbaycan', en: 'Azerbaijan' },
  { code: 'BS', native: 'Bahamas', en: 'Bahamas' },
  { code: 'BH', native: 'البحرين', en: 'Bahrain' },
  { code: 'BD', native: 'বাংলাদেশ', en: 'Bangladesh' },
  { code: 'BB', native: 'Barbados', en: 'Barbados' },
  { code: 'BY', native: 'Беларусь', en: 'Belarus' },
  { code: 'BE', native: 'België', en: 'Belgium' },
  { code: 'BZ', native: 'Belize', en: 'Belize' },
  { code: 'BJ', native: 'Bénin', en: 'Benin' },
  { code: 'BT', native: 'འབྲུག', en: 'Bhutan' },
  { code: 'BO', native: 'Bolivia', en: 'Bolivia' },
  { code: 'BA', native: 'Bosna i Hercegovina', en: 'Bosnia and Herzegovina' },
  { code: 'BW', native: 'Botswana', en: 'Botswana' },
  { code: 'BR', native: 'Brasil', en: 'Brazil' },
  { code: 'BN', native: 'Brunei', en: 'Brunei' },
  { code: 'BG', native: 'България', en: 'Bulgaria' },
  { code: 'BF', native: 'Burkina Faso', en: 'Burkina Faso' },
  { code: 'BI', native: 'Burundi', en: 'Burundi' },
  { code: 'CV', native: 'Cabo Verde', en: 'Cabo Verde' },
  { code: 'KH', native: 'កម្ពុជា', en: 'Cambodia' },
  { code: 'CM', native: 'Cameroun', en: 'Cameroon' },
  { code: 'CA', native: 'Canada', en: 'Canada' },
  { code: 'CF', native: 'Centrafrique', en: 'Central African Republic' },
  { code: 'TD', native: 'Tchad', en: 'Chad' },
  { code: 'CL', native: 'Chile', en: 'Chile' },
  { code: 'CN', native: '中国', en: 'China' },
  { code: 'CO', native: 'Colombia', en: 'Colombia' },
  { code: 'KM', native: 'Comores', en: 'Comoros' },
  { code: 'CG', native: 'Congo', en: 'Congo' },
  { code: 'CD', native: 'Congo (RDC)', en: 'Congo (DRC)' },
  { code: 'CR', native: 'Costa Rica', en: 'Costa Rica' },
  { code: 'HR', native: 'Hrvatska', en: 'Croatia' },
  { code: 'CU', native: 'Cuba', en: 'Cuba' },
  { code: 'CY', native: 'Κύπρος', en: 'Cyprus' },
  { code: 'CZ', native: 'Česko', en: 'Czechia' },
  { code: 'DK', native: 'Danmark', en: 'Denmark' },
  { code: 'DJ', native: 'Djibouti', en: 'Djibouti' },
  { code: 'DM', native: 'Dominica', en: 'Dominica' },
  { code: 'DO', native: 'República Dominicana', en: 'Dominican Republic' },
  { code: 'EC', native: 'Ecuador', en: 'Ecuador' },
  { code: 'EG', native: 'مصر', en: 'Egypt' },
  { code: 'SV', native: 'El Salvador', en: 'El Salvador' },
  { code: 'GQ', native: 'Guinea Ecuatorial', en: 'Equatorial Guinea' },
  { code: 'ER', native: 'ኤርትራ', en: 'Eritrea' },
  { code: 'EE', native: 'Eesti', en: 'Estonia' },
  { code: 'SZ', native: 'Eswatini', en: 'Eswatini' },
  { code: 'ET', native: 'ኢትዮጵያ', en: 'Ethiopia' },
  { code: 'FJ', native: 'Fiji', en: 'Fiji' },
  { code: 'FI', native: 'Suomi', en: 'Finland' },
  { code: 'FR', native: 'France', en: 'France' },
  { code: 'GA', native: 'Gabon', en: 'Gabon' },
  { code: 'GM', native: 'Gambia', en: 'Gambia' },
  { code: 'GE', native: 'საქართველო', en: 'Georgia' },
  { code: 'DE', native: 'Deutschland', en: 'Germany' },
  { code: 'GH', native: 'Ghana', en: 'Ghana' },
  { code: 'GR', native: 'Ελλάδα', en: 'Greece' },
  { code: 'GD', native: 'Grenada', en: 'Grenada' },
  { code: 'GT', native: 'Guatemala', en: 'Guatemala' },
  { code: 'GN', native: 'Guinée', en: 'Guinea' },
  { code: 'GW', native: 'Guiné-Bissau', en: 'Guinea-Bissau' },
  { code: 'GY', native: 'Guyana', en: 'Guyana' },
  { code: 'HT', native: 'Haïti', en: 'Haiti' },
  { code: 'HN', native: 'Honduras', en: 'Honduras' },
  { code: 'HU', native: 'Magyarország', en: 'Hungary' },
  { code: 'IS', native: 'Ísland', en: 'Iceland' },
  { code: 'IN', native: 'भारत', en: 'India' },
  { code: 'ID', native: 'Indonesia', en: 'Indonesia' },
  { code: 'IR', native: 'ایران', en: 'Iran' },
  { code: 'IQ', native: 'العراق', en: 'Iraq' },
  { code: 'IE', native: 'Éire', en: 'Ireland' },
  { code: 'IL', native: 'ישראל', en: 'Israel' },
  { code: 'IT', native: 'Italia', en: 'Italy' },
  { code: 'CI', native: "Côte d'Ivoire", en: 'Ivory Coast' },
  { code: 'JM', native: 'Jamaica', en: 'Jamaica' },
  { code: 'JP', native: '日本', en: 'Japan' },
  { code: 'JO', native: 'الأردن', en: 'Jordan' },
  { code: 'KZ', native: 'Қазақстан', en: 'Kazakhstan' },
  { code: 'KE', native: 'Kenya', en: 'Kenya' },
  { code: 'KI', native: 'Kiribati', en: 'Kiribati' },
  { code: 'KW', native: 'الكويت', en: 'Kuwait' },
  { code: 'KG', native: 'Кыргызстан', en: 'Kyrgyzstan' },
  { code: 'LA', native: 'ລາວ', en: 'Laos' },
  { code: 'LV', native: 'Latvija', en: 'Latvia' },
  { code: 'LB', native: 'لبنان', en: 'Lebanon' },
  { code: 'LS', native: 'Lesotho', en: 'Lesotho' },
  { code: 'LR', native: 'Liberia', en: 'Liberia' },
  { code: 'LY', native: 'ليبيا', en: 'Libya' },
  { code: 'LI', native: 'Liechtenstein', en: 'Liechtenstein' },
  { code: 'LT', native: 'Lietuva', en: 'Lithuania' },
  { code: 'LU', native: 'Luxembourg', en: 'Luxembourg' },
  { code: 'MG', native: 'Madagasikara', en: 'Madagascar' },
  { code: 'MW', native: 'Malawi', en: 'Malawi' },
  { code: 'MY', native: 'Malaysia', en: 'Malaysia' },
  { code: 'MV', native: 'ދިވެހިރާއްޖެ', en: 'Maldives' },
  { code: 'ML', native: 'Mali', en: 'Mali' },
  { code: 'MT', native: 'Malta', en: 'Malta' },
  { code: 'MH', native: 'Marshall Islands', en: 'Marshall Islands' },
  { code: 'MR', native: 'موريتانيا', en: 'Mauritania' },
  { code: 'MU', native: 'Maurice', en: 'Mauritius' },
  { code: 'MX', native: 'México', en: 'Mexico' },
  { code: 'FM', native: 'Micronesia', en: 'Micronesia' },
  { code: 'MD', native: 'Moldova', en: 'Moldova' },
  { code: 'MC', native: 'Monaco', en: 'Monaco' },
  { code: 'MN', native: 'Монгол', en: 'Mongolia' },
  { code: 'ME', native: 'Crna Gora', en: 'Montenegro' },
  { code: 'MA', native: 'المغرب', en: 'Morocco' },
  { code: 'MZ', native: 'Moçambique', en: 'Mozambique' },
  { code: 'MM', native: 'မြန်မာ', en: 'Myanmar' },
  { code: 'NA', native: 'Namibia', en: 'Namibia' },
  { code: 'NR', native: 'Nauru', en: 'Nauru' },
  { code: 'NP', native: 'नेपाल', en: 'Nepal' },
  { code: 'NL', native: 'Nederland', en: 'Netherlands' },
  { code: 'NZ', native: 'New Zealand', en: 'New Zealand' },
  { code: 'NI', native: 'Nicaragua', en: 'Nicaragua' },
  { code: 'NE', native: 'Niger', en: 'Niger' },
  { code: 'NG', native: 'Nigeria', en: 'Nigeria' },
  { code: 'KP', native: '조선', en: 'North Korea' },
  { code: 'MK', native: 'Северна Македонија', en: 'North Macedonia' },
  { code: 'NO', native: 'Norge', en: 'Norway' },
  { code: 'OM', native: 'عُمان', en: 'Oman' },
  { code: 'PK', native: 'پاکستان', en: 'Pakistan' },
  { code: 'PW', native: 'Palau', en: 'Palau' },
  { code: 'PS', native: 'فلسطين', en: 'Palestine' },
  { code: 'PA', native: 'Panamá', en: 'Panama' },
  { code: 'PG', native: 'Papua New Guinea', en: 'Papua New Guinea' },
  { code: 'PY', native: 'Paraguay', en: 'Paraguay' },
  { code: 'PE', native: 'Perú', en: 'Peru' },
  { code: 'PH', native: 'Pilipinas', en: 'Philippines' },
  { code: 'PL', native: 'Polska', en: 'Poland' },
  { code: 'PT', native: 'Portugal', en: 'Portugal' },
  { code: 'QA', native: 'قطر', en: 'Qatar' },
  { code: 'RO', native: 'România', en: 'Romania' },
  { code: 'RW', native: 'Rwanda', en: 'Rwanda' },
  { code: 'KN', native: 'Saint Kitts and Nevis', en: 'Saint Kitts and Nevis' },
  { code: 'LC', native: 'Saint Lucia', en: 'Saint Lucia' },
  { code: 'VC', native: 'Saint Vincent', en: 'Saint Vincent and the Grenadines' },
  { code: 'WS', native: 'Samoa', en: 'Samoa' },
  { code: 'SM', native: 'San Marino', en: 'San Marino' },
  { code: 'ST', native: 'São Tomé e Príncipe', en: 'São Tomé and Príncipe' },
  { code: 'SA', native: 'السعودية', en: 'Saudi Arabia' },
  { code: 'SN', native: 'Sénégal', en: 'Senegal' },
  { code: 'RS', native: 'Србија', en: 'Serbia' },
  { code: 'SC', native: 'Seychelles', en: 'Seychelles' },
  { code: 'SL', native: 'Sierra Leone', en: 'Sierra Leone' },
  { code: 'SG', native: 'Singapore', en: 'Singapore' },
  { code: 'SK', native: 'Slovensko', en: 'Slovakia' },
  { code: 'SI', native: 'Slovenija', en: 'Slovenia' },
  { code: 'SB', native: 'Solomon Islands', en: 'Solomon Islands' },
  { code: 'SO', native: 'Soomaaliya', en: 'Somalia' },
  { code: 'ZA', native: 'South Africa', en: 'South Africa' },
  { code: 'KR', native: '대한민국', en: 'South Korea' },
  { code: 'SS', native: 'South Sudan', en: 'South Sudan' },
  { code: 'ES', native: 'España', en: 'Spain' },
  { code: 'LK', native: 'ශ්‍රී ලංකාව', en: 'Sri Lanka' },
  { code: 'SD', native: 'السودان', en: 'Sudan' },
  { code: 'SR', native: 'Suriname', en: 'Suriname' },
  { code: 'SE', native: 'Sverige', en: 'Sweden' },
  { code: 'CH', native: 'Schweiz', en: 'Switzerland' },
  { code: 'SY', native: 'سوريا', en: 'Syria' },
  { code: 'TW', native: '臺灣', en: 'Taiwan' },
  { code: 'TJ', native: 'Тоҷикистон', en: 'Tajikistan' },
  { code: 'TZ', native: 'Tanzania', en: 'Tanzania' },
  { code: 'TH', native: 'ไทย', en: 'Thailand' },
  { code: 'TL', native: 'Timor-Leste', en: 'Timor-Leste' },
  { code: 'TG', native: 'Togo', en: 'Togo' },
  { code: 'TO', native: 'Tonga', en: 'Tonga' },
  { code: 'TT', native: 'Trinidad and Tobago', en: 'Trinidad and Tobago' },
  { code: 'TN', native: 'تونس', en: 'Tunisia' },
  { code: 'TR', native: 'Türkiye', en: 'Turkey' },
  { code: 'TM', native: 'Türkmenistan', en: 'Turkmenistan' },
  { code: 'TV', native: 'Tuvalu', en: 'Tuvalu' },
  { code: 'UG', native: 'Uganda', en: 'Uganda' },
  { code: 'UA', native: 'Україна', en: 'Ukraine' },
  { code: 'AE', native: 'الإمارات', en: 'United Arab Emirates' },
  { code: 'GB', native: 'United Kingdom', en: 'United Kingdom' },
  { code: 'US', native: 'United States', en: 'United States' },
  { code: 'UY', native: 'Uruguay', en: 'Uruguay' },
  { code: 'UZ', native: 'Oʻzbekiston', en: 'Uzbekistan' },
  { code: 'VU', native: 'Vanuatu', en: 'Vanuatu' },
  { code: 'VA', native: 'Vaticano', en: 'Vatican City' },
  { code: 'VE', native: 'Venezuela', en: 'Venezuela' },
  { code: 'VN', native: 'Việt Nam', en: 'Vietnam' },
  { code: 'YE', native: 'اليمن', en: 'Yemen' },
  { code: 'ZM', native: 'Zambia', en: 'Zambia' },
  { code: 'ZW', native: 'Zimbabwe', en: 'Zimbabwe' },
]

